import Head from 'next/head'
import { useState } from 'react'
import { useUser } from '../hooks/user.hook'

export default function Home() {
  const [userId, setUserId] = useState(1);
  
  const { data, isLoading, error } = useUser(userId)

  function fetchAnotherUser () {
    setUserId(prevUserId => prevUserId + 1)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello {isLoading ? 'Loading...' : data?.name}</h1>

      <button onClick={fetchAnotherUser}>Fetch another user</button>
    </>
  )
}
